### ISSUE TITLE
Permission to host the tutorials on a zeronet site

### ISSUE THREAD

**Issue by trenta3** [imachug/The-Truth-about-ZeroNet#3]
Hi! Your tutorials are really great, and I'd like to also host them on a [wiki in ZeroNet](http://127.0.0.1:43110/18hFUweFE3AJwZWnaMeq3fJMobrq8jevfd/?Page:home) under the Creative Commons Attributions-Sharealike licence.
Since I couldn't find any licence notice on them, I'm asking you if it is possible.

Also I'd like the posted content not to become old so let me know if you are already hosting them on ZeroNet in a readable form (with rendered markdown) and/or if you have other ideas in order not to have sync issues between all the places where they are.

**Comment by imachug** [comment]
No problem! Just make sure to link to the original repo, so others could make some requests. Nice wiki, btw!

**Comment by trenta3** [comment]
Thank you. I've added them with a link.
