### ISSUE TITLE
Proxy list is outdated

### ISSUE THREAD

**Issue by scsmash3r** [imachug/The-Truth-about-ZeroNet#5]
Example link: https://github.com/imachug/The-Truth-about-ZeroNet/blob/master/3.%20cloning%20zites.md
None of proxies work =(

**Comment by imachug** [comment]
That's sad. Do you know of any working proxies?

**Comment by scsmash3r** [comment]
> That's sad. Do you know any working proxies?

Two working ones at the moment:
https://zero.acelewis.com/
https://0net-preview.duckdns.org/

**Comment by imachug** [comment]
Awesome. Could you please make a PR that adds those proxies?

**Comment by scsmash3r** [comment]
https://github.com/imachug/The-Truth-about-ZeroNet/pull/6

**Comment by imachug** [comment]
Thanks, merged!
